spring:
  application:
    name: spring-cloud-gateway-demo
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #启用路由访问
          lower-case-service-id: true #启动服务名小写
      routes:
        - id: spring-cloud-client-demo
          uri: lb://spring-cloud-client-demo
          predicates:
            - Path=/client/**
#            - Method=GET,POST
#            - Header=X-Request-Id, \d+
#            - User=mt
            - Weight=group1, 2
          filters:
            - AddRequestHeader=X-Request-Foo, Bar
            - StripPrefix=1
            - SaveSession
        - id: spring-cloud-client-demo1
          uri: lb://spring-cloud-client-demo
          predicates:
            - Path=/client/**
            - Weight=group1, 8
          filters:
            - StripPrefix=2
        - id: proxy
          uri: http://localhost:8801
          predicates:
            - Path=/demo/**
            - Weight=group2, 8
        - id: proxy1
          uri: http://localhost:8801
          predicates:
            - Path=/demo/**
            - Weight=group2, 2
          filters:
            - StripPrefix=1
        - id: spring-cloud-client-demo2
          uri: lb://spring-cloud-client-demo
          predicates:
            - Path=/cloud/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
                key-resolver: "#{@myKeyResolver}"
        - id: spring-cloud-client-demo3
          uri: lb://spring-cloud-client-demo
          predicates:
            - Path=/websocket/**
          filters:
            - StripPrefix=1
  redis:
    host: localhost
    port: 6379
    database: 1
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 1
    password: 123456
  mvc:
    throw-exception-if-no-handler-found: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 20
server:
  port: 10001